### ISSUE TITLE
SPIKE: "This module should allow connected authenticator modules to be 'version agnostic'"

### ISSUE THREAD

**Issue by brynwhyman** [Firesphere/silverstripe-bootstrapmfa#55]
Our intention with this module is that it is built in a way that allows connecting authentication modules (`elliot-sawyer/totp-authenticator`) to be 'version agnostic', i.e they have one version, and the bootstrap module handles compatibility for SS3 or SS4.

While this has been scoped and is assumed to work, we should architect this (with a proof of concept) to confirm that this is a viable (and the preferred) approach.

Outcomes of this SPIKE:
1. Establish responsibilities of the authenticator modules
2. Understand if 'version agnostic' is possible
3. Decide if this is an approach we want to proceed with, or if each authenticator module has two versions for SS3 and SS4

**Comment by brynwhyman** [comment]
Other thoughts:
- How will React components built for V4 admin work with V3 admin?

**Comment by ScopeyNZ** [comment]
> How will React components built for V4 admin work with V3 admin?

With that thought - do we need to build the same components for V3 as we do for V4 considering our acceptance criteria is a little different for V3?

**Comment by NightJar** [comment]
# Results

OK, so in the end this has taken several forms and more of an evaluation than planned. We've discussed it as a (present in person) team, a little periphery context shared with @robbieaverill - so this is a summary of all, and a chance for @robbieaverill to give a reasonably impartial evaluation of the situation.

## Precontext:

In order to know if this is possible, it is first necessary to understand the responsibilities of an `Authenticator`.

Currently an authenticator does two things:
1. Provide a form to accept an MFA token
2. Authenticate a given token.

This takes place as a part of a two step process as a delegate of the 'actual' SilverStripe authenticator, which is responsible for providing and evaluating the initial step of MFA (username:password). Upon success it then proceeds to step two, where it asks for the MFA form from all enabled authenticators, leaving it to the front end to decide which is shown or hidden (and the interface for altering that).
The submission is POSTed back to the bootstrap form handler, which then delegates to the appropriate `MFAAuthenticator` based on which form was submitted.

Implementation of MFA Authenticators is currently amidst transition between extending an abstract super class to implementing an interface - so if you look at code it may not be immediately clear.

## Givens

With the above info we know the following:

Subclasses are possible (since these are not DataObjects), but interfaces are less impactful on the system in SilverStripe 3. We must use namespaces in order to not have to 'change' anything between SilverStripe 3 and SilverStripe 4 support (so far as the Authenticator is concerned).

Translations are fine because `_t` is consistent between the two versions.

The classes we need to rely upon (e.g. for building) will be different between versions though. So we need a way around this:
- Use `Injector` extensively referring to either contextual services `Form.MFA` or non-conflicting service names that refer to the correct class (e..g `MFAForm: Form`) - this can be controlled via configuration in the bootstrap module.
- Pass closures around accepting e.g. Form, FormField, etc. as parameters and using them to modify a given form.
- create factory classes or methods, taking a form of configuration and returning the correctly built form to represent the authenticator.
- Create a very very defined `interface` to return the relevant _pieces_ that make up the form - as all authenticator token forms will have at heart a single text field.

I dismissed the closure and factory ideas (which admittedly are very similar) as they would generally require either undocumented interfaces (closures), or a configuration DSL to be created for Forms... which would then be weird and specific to this module. I feel like if this ever happens it should be in core (or some kind of wider core module like GraphQL is).

## Considerations

Given that the majority (all) of the complexity comes from attempting to support the supply of an entire form, it causes one to think.

- Could we get away with a DataObject-like `getFields` only?
- Is there ever more than one field? (short answer: no.)
- If there is never more than one field, why even have a form? Just validate the submission?
- consider the designs [for logging in](https://projects.invisionapp.com/share/3PNSKZQYBJZ#/screens/321188001) - here we can see why the authenticator provides the form - it is the easiest way for it to give context.
- There are other flows such as enabling a particular authenticator for a user (the setup process) to consider too, this investigation (too) narrowly focused on the log in flow only
- Architecture is something we may wish to change as we uncover more about this setup in future investigations (e.g. grooming tasks, not just spikes).

## Options

So given that we have two options left; Intense `Injector` usage, or strict `interface` adherence.

### Injector

No particular barrier here, but code would look a little messy having what would normally be e.g. `Form::create($name, ...)` become `$injector->createWithArgs('Form.MFA', [ $name, ... ])`

It does however rely on the Form (and FormField, and FieldList, etc.) interface remaining rather consistent between versions, along with the class relationship between them all.
This is mostly true I think, but may not always be the case if this pattern continues upwards with SS5, etc.

This would however require us to _pass_ Injector into the `getForm` interface method, in order to get around the namespace differences between the two SilverStripe versions in question.

### Interface

@ScopeyNZ pointed out that this removes all uncertainty to somewhat undocumented interfaces (Injector could actually return anything, not a Form as we know it), which is rather nice. There is no reliance on any other SilverStripe direct class or function, beyond perhaps `_t`.

This interface would require such methods as:
- `getTitle`
- `getShortDescription`
- `getLongDescription` (or `getUserHelpLink`)
- `getTokenFieldTitle`
- `getTokenFieldHint` (or `getTokenFieldAttributes`
- `getShowNextButton`
- `getExtraRequirements` (e.g. JavaScript libraries for WebAuthn)

This is verbose and has very limited flexibility. But it would require an authenticator to consider all of these, even if some return an empty string or null etc.

This method would however grow in complexity the more responsibility an authenticator class has... as it is they break SRP (as much of SS does...), perhaps we should consider this as a good way to enforce nice design? I dunno... pros and cons.

# Conclusion

There is a lot going on here, more so than first thought. The decoupling of the framework version from the authenticator implementation is certainly _possible_, but as with many spikes the main question here is _should_ we, not just _could_ we.

Unfortunately I feel it is still too open a question to answer at this time, as much of the chosen response will depend on two factors: team feel as a whole, and investigation into the current architecture in the rest of this module. I think that we cannot make an appropriate decision about direction without first having full context over what is, and what needs to happen with the module as a whole.

Initially I was leaning towards Injector use as a quick win.
Then more and more to interfaces as we should make some minor architecture adjustments in places (e.g. perhaps an AuthenticatorFormProvider interface an having the Authenticator interface only do authentication...)
Now I'm thinking perhaps as the complexity seems to quickly escalate that perhaps it's just not worth it.

But without full context on the rest of the work we have to do, and what that entails to achieve the desired outcomes... maybe there's time in the bank for smoothing design, maybe not.

@brynwhyman @robbieaverill @ScopeyNZ @Cheddam

**Comment by robbieaverill** [comment]
>* as all authenticator token forms will have at heart a single text field.

Yubikey won't, but I suppose it will have a hidden input field.

>* Create a very very defined `interface` to return the relevant _pieces_ that make up the form - as all authenticator token forms will have at heart a single text field.

I have a feeling that we could probably use a combination of more than one of these ideas.

We'll totally need an interface to provide to authenticator modules, no question about that.

I assume that the bootstrap module will need to extend core SilverStripe classes at some point - that might get hairy when they either have or have not got a namespace. We may be able to get around that by using shim classes like:

```php
# File: src/Compat/Form.php
namespace BootstrapMFA\Compat;

if (class_exists(\Form::class)) {
    // SS3 compatibility
    class Form extends \Form {}
} else {
    // SS4 compatibility
    class Form extends \SilverStripe\Forms\Form {}
}
```

This might let us then do something like `BootstrapMFAForm extends \BootstrapMFA\Compat\Form` and let the shim class handle which it should extend. Note that @ScopeyNZ has previously raised concerns about PHP parsing the file contents before it actually executes the conditions, and it's also not pretty code (but to an extent we can't expect it all to be when we're doing this anyway). I've seen this done in Magento modules before so it would be an option.

You obviously don't have a guarantee of API signature compatibility by doing this, and extending any method with class typehints wouldn't work either since they'd be different between SS3 and SS4.

I guess we need to rely on extension points in core as much as possible.

>* Is there ever more than one field? (short answer: no.)

This seems like a dangerous assumption to make to me.

>* There are other flows such as enabling a particular authenticator for a user (the setup process) to consider too, this investigation (too) narrowly focused on the log in flow only

Good point.

>It does however rely on the Form (and FormField, and FieldList, etc.) interface remaining rather consistent between versions, along with the class relationship between them all.

As noted above, this isn't necessarily the case and it's risky for us to build assumptions in that it would be. One example is type hinting in method signatures.

>This would however require us to _pass_ Injector into the `getForm` interface method, in order to get around the namespace differences between the two SilverStripe versions in question.

This doesn't sound feasible to me, given that it would require a core enhancement to be made.

>as it is they break SRP (as much of SS does...)

This whole idea by definition breaks SRP 😆 

---

How about something like this:

* silverstripe/bootstrap-mfa-bindings module:
  * 1 branch: handles the necessary bindings for SS3 classes e.g. Form, Member, etc (anything with namespaces)
  * as above, for SS4
* firesphere/silverstripe-bootstrapmfa: requires _either_ silverstripe/bootstrap-mfa-bindings version `^1 || ^2`
* elliot-sawyer/totp-authenticator requires firesphere/silverstripe-bootstrapmfa ^1

This way we can put as much of our business logic as possible into well structured service definitions and interfaces in the BootstrapMFA module, while keeping the minimum amount of SS3/SS4 core class bindings confined to respective branches in a separate module.

This would allow authenticator modules to require a single version of BootstrapMFA and we'd hide the complexity by providing simpler interfaces from here outward (like the suggestion above @ScopeyNZ is noted in).

---

Have we considered the frontend app at all? In SS4 we're going to implement it in React (right?) even though it's a frontend app. I guess we can do this safely in SS3 as well provided that we allow the API endpoints to be configurable (or entirely the same between SS3 + SS4).

---

I guess the only way we're going to know if we _can_ do this is by trying it with a proof of concept.

Personally I still think we're going to spend more time trying to do this than we would maintaining two separate versions of this module (and the authenticators we'll be supporting).

Good write up! 👍

**Comment by ScopeyNZ** [comment]
Although I might have bias, I think the only way we can do this is by having ta few interfaces that bootstrap-mfa consumes to build forms and authenticate. This might mean it takes the same amount of time it would to just build two versions of each authenticator module, but part of the long-term goal here should be that it's really easy to add new authenticators.

I've put some thought into what these interfaces might look like, and if it sounds too complex then I don't think this idea is worth it:

```
LoginFormInterface
- getTitle
- getShortDescription
- getUserHelpLink
- getTokenFieldTitle
- updateTokenFieldAttributes
- isNextButtonShown
- getExtraRequirements

RegistrationFormInterface
- getSteps
- getSchemaFromResponse

AuthenticatorInterface
- verify
```

Some form of `RegistrationFormInterface` would be the most complicated part. Registration is often two step. Take TOTP for example; step 1, show a QR code, step 2, provide an input so you can confirm the code. U2F would be a single step though. I put in `getSteps` thinking the return type could be `StepInterface[]`:

```
StepInterface
- getTitle
- getShortDescription
- getUserHelpLink
- getTokenFieldTitle
- updateTokenFieldAttributes
- getContent
- isNextButtonShown
- getExtraRequirements
```

Look familiar? The only problem here is `getContent` now runs into the problem where we need to have it template-able. Maybe it makes more sense to have `getContentData` and `getContentTemplate`. Then for `silverstripe-login-forms` we can ignore `getContentTemplate` and just have our own components (assuming React) for authenticators...

Is this crazy? I think it's achievable. It seems a bit clunky, but imagine making a brand new authenticator now... All you have to do it implement the interfaces which should be self-documenting. I think that's better than the current state that requires authenticators to write their own `MemberExtension`.

As an aside I think supporting multiple MFA through each method providing it's own `MemberExtension` really confusing. I think it makes way more sense as a `hasMany` relationship.

**Comment by NightJar** [comment]
> > * as all authenticator token forms will have at heart a single text field.
> 
> Yubikey won't, but I suppose it will have a hidden input field.

Yup ;)
 
> We'll totally need an interface to provide to authenticator modules, no question about that.

Indeed, the question posed is more about how far we go with that/these interface/interfaces.

> I assume that the bootstrap module will need to extend core SilverStripe classes at some point - that might get hairy when they either have or have not got a namespace.

Ah, sorry for confustion. It sounds like you're confusing the point of this spike, I guess I didn't make that clear in my opening.

The module this issue is written on is `bootstrapmfa`, yep, but this spike is actually for [composite](https://www.visual-paradigm.com/guide/uml-unified-modeling-language/uml-aggregation-vs-composition/) classes that handle the different authentication types (e.g. SMS, OTP, TOTP, U2F)

In this spike we're looking at having this bootstrap module be two separate versions between the versions of SilverStripe, but reducing maintenance burden by having each/all _authenticators_ be independent of SilverStripe version; We would only have to write them once (and maintain one version).

> This might let us then do something like `BootstrapMFAForm extends \BootstrapMFA\Compat\Form` and let the shim class handle which it should extend.

I had considered this as well actually, but hadn't taken notes on it. I considered it easier/cleaner to make the 'shim class' as an Injector service. However thinking about this again now I see one small (tiny) advantage in that we could then have control over a more defined interface, and being able to bridge variances in Form, FormField, etc. between versions with such an approach.

As a side note I've seen [CodeIgniter](https://github.com/bcit-ci/CodeIgniter/blob/2.2.6/system/database/DB.php#L128-L138) do this too, which was entirely horrible in practice. The project ended up with classes extending a non-existent super class.

> This seems like a dangerous assumption to make to me.

True, I agree. However we double checked with our ITSM and there were two points:
- Each factor is usually a single step.
- Each point is done one at a time otherwise you end up with frustration and horrible UX around time based authentications such as TOTP expiring while one is e.g. checking their email or waiting for an SMS for another factor.
- There are no currently known methods that use more than one entry. Some require a combination of two inputs... but then combine it as a single input via concatenation. E.g. an hardware token fob for an account that also has a pin. One enters their token and then the pin into a single field.

> > It does however rely on the Form (and FormField, and FieldList, etc.) interface remaining rather consistent between versions, along with the class relationship between them all.
> 
> As noted above, this isn't necessarily the case and it's risky for us to build assumptions in that it would be. One example is type hinting in method signatures.

True, but I was also keeping in mind that hopefully we would end up consuming very little of such interfaces (thereby reducing potential issue).

I considered this when quickly trying to smack up a PoC (which I abandoned), type hints would have to be omitted, and doc blocks wouldn't truly reflect their expectations either.

> > This would however require us to _pass_ Injector into the `getForm` interface method, in order to get around the namespace differences between the two SilverStripe versions in question.
> 
> This doesn't sound feasible to me, given that it would require a core enhancement to be made.

Would it? I don't follow the logic here sorry. Could you please expand?

> > as it is they break SRP (as much of SS does...)
> 
> This whole idea by definition breaks SRP 😆

🤔 Not sure... could you expand?

> How about something like this:
> 
> * silverstripe/bootstrap-mfa-bindings module:
>   
>   * 1 branch: handles the necessary bindings for SS3 classes e.g. Form, Member, etc (anything with namespaces)
>   * 2 branch: as above, for SS4
> * firesphere/silverstripe-bootstrapmfa: requires _either_ silverstripe/bootstrap-mfa-bindings version `^1 || ^2`. The API interfaces for the bindings module would be the same in both versions - think of it like a SS version agnostic proxy module...
> * elliot-sawyer/totp-authenticator requires firesphere/silverstripe-bootstrapmfa ^1
> 
> This way we can put as much of our business logic as possible into well structured service definitions and interfaces in the BootstrapMFA module, while keeping the minimum amount of SS3/SS4 core class bindings confined to respective branches in a separate module.
> 
> This would allow authenticator modules to require a single version of BootstrapMFA and we'd hide the complexity by providing simpler interfaces from here outward (like the suggestion above @ScopeyNZ is noted in).

I'm not sure I completely followed that, it sounds like complexity is growing exponentially. I think it's feasible to have the authenticators be agnostic via a well defined interface, I don't see much reason for abstracting and proxying/bridging interfaces between versions unless it becomes necessary, and we haven't worked around it in various approaches (e.g. @ScopeyNZ's suggestion where _none_ of the Form API is consumed). I think it's important again to note that we're looking at the authenticators specifically, not this bootstrap module. Are you worried about labelling dependencies between them with the likes of composer?

> Have we considered the frontend app at all? In SS4 we're going to implement it in React (right?) even though it's a frontend app. I guess we can do this safely in SS3 as well provided that we allow the API endpoints to be configurable (or entirely the same between SS3 + SS4).

Nope.

> Personally I still think we're going to spend more time trying to do this than we would maintaining two separate versions of this module (and the authenticators we'll be supporting).

That was sort of the conclusion I was trending to, too :)

> Good write up! 👍

Thanks :)

**Comment by NightJar** [comment]
> Is this crazy? I think it's achievable. It seems a bit clunky, but imagine making a brand new authenticator now... All you have to do it implement the interfaces which should be self-documenting. I think that's better than the current state that requires authenticators to write their own `MemberExtension`.
> 
> As an aside I think supporting multiple MFA through each method providing it's own `MemberExtension` really confusing. I think it makes way more sense as a `hasMany` relationship.

I also think it's achievable. But you're right in that it does seem a little clunky. I suppose my only other reservation is that it seems/feels a little like when new developers work around a framework rather than with it. We have all these helpers and methods available to us for building forms, but then we're going to build our own interface for a specific use case. In this case it makes sense (for good reasons), but does it set some kind of precedence? I dunno. It is totally OK, but... some kind of reservation there. Although I'd be totally find doing this and it would ultimately result in quite a nice solution.

I guess it comes into weighing up value vs effort, which is ultimately the goal of this spike.

🤷‍♂️

**Comment by ScopeyNZ** [comment]
Perhaps this really is a pipe dream for now. If we boil it down to pros and cons...

Advantages:
- Way easier to implement MFA methods - which is an advantage for community too
- Much easier to maintain (including future upgrades)
- API of BootstrapMFA module can be more restricted (maybe making it easier to maintain)
Disadvantages:
- Takes a bit longer to do :sweat_smile:
- Bootstrap MFA module will probably end up being complicated
- Having to create a new version of BootstrapMFA might be more difficult (but would be better considering you don't have to upgrade authenticator modules)

Considering we're looking to have TOTP and U2F commercially supported it's certainly "faster" not to bother with this. Just need to decide whether reducing future efforts is worth spending time on now.

**Comment by Cheddam** [comment]
I think it's worth developing a more in-depth plugin API for the MFA client modules first and independently from version-agnostic support. It would give us some of the advantages listed above (easier client module development for us + community), and ease development of the SS3-compatible implementation if/when we decide to go ahead with it (with the client modules no longer being tied to any core APIs, we should only need to modify the Bootstrap module itself).

**Comment by ScopeyNZ** [comment]
> I think it's worth developing a more in-depth plugin API for the MFA client modules

I whole-heartedly agree with this. Even if we ditch the "framework agnostic" idea we still need better interfaces. If we ditch this I think we'll still need an interface for providing a login form and one for providing _multiple_ registration forms and another for verification. 

Currently (especially when it comes to registration) the API is just a little too awkward to easily support the UI as designed. Additionally I don't think that the current architecture allows for a decent UX at all (at least without strange hacks) - especially as the number of MFA types supported grows.

**Comment by ScopeyNZ** [comment]
I've raised an "RFC" about interfaces in #59

**Comment by Firesphere** [comment]
> > > * as all authenticator token forms will have at heart a single text field.
> 
> 
> > Yubikey won't, but I suppose it will have a hidden input field.

> Yup ;)

Yes, it does, Yubikey, both old style and new style U2F require a form. One is hidden, the other visible, but there should be a form that handles the submission. This is hard to bypass, even Yubico etc. have made it form based. The difference is that the contents are a binary, invisible to the user, versus a visible field.

Here's a thought. What about maintaining two versions until SS3 support is phased out? From that point onward, looking at the future is easier. If it takes away a strain of maintenance, I don't see why an SS3 version for all authenticators, to be abandoned unless security issues arise, is actually a bad idea.

I'm all for @Cheddam's idea!
